apiVersion: apps/v1
kind: Deployment
metadata:
  name: merged-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merged-app
  template:
    metadata:
      labels:
        app: merged-app
    spec:
      containers:
        - name: merged-app
          image: shubhamskadam89/growgrade-combined:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 10000
